// starter-web-react/src/components/App.js
import React, {Component} from 'react';

export default class App extends Component {
  state = {foo: 'bar', clickCount: 0};

  componentDidMount() {
    this.getHello().then((val) => {
      if (val) {
        this.setState({foo: val});
      }
    });
  }

  getHello = async () => {
    const res = await fetch('/api/hello');
    if (res.ok) {
      return res.text();
    }
    return undefined;
  };

  handleClick = (e) => {
    e.preventDefault();
    this.setState({clickCount: this.state.clickCount + 1});
  };

  render() {
    const {foo, clickCount} = this.state;
    return (
      <div>
        {foo}
        <button className="btn btn-secondary" onClick={this.handleClick}>Click count: {clickCount}</button>
      </div>
    );
  }
}

// starter-web-vue/src/components/App.vue
<template>
  <div>
    {{foo}}
    <button class="btn btn-secondary" @click="handleClick">Click count: {{clickCount}}</button>
  </div>
</template>
<script>
  export default {
    data() {
      return {foo: 'bar', clickCount: 0};
    },
    mounted() {
      this.getHello().then(val => {
        if (val) {
          this.foo = val;
        }
      });
    },
    methods: {
      handleClick(e) {
        e.preventDefault();
        this.clickCount++;
      },
      getHello: async () => {
        const res = await fetch('/api/hello');
        if (res.ok) {
          return res.text();
        }
        return undefined;
      },
    },
  };
</script>
